# Generated by Django 2.2.6 on 2019-11-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100, verbose_name='mv_name')),
                ('aexprc', models.IntegerField(verbose_name='mv_name')),
                ('active', models.CharField(default='Y', max_length=100, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('pincode', models.IntegerField(verbose_name='pincode')),
                ('active', models.CharField(default='Y', max_length=100, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100, verbose_name='d_name')),
                ('dexprc', models.IntegerField(verbose_name='d_exprc')),
                ('active', models.CharField(default='Y', max_length=100, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvname', models.CharField(max_length=100, verbose_name='mv_name')),
                ('mvreviews', models.CharField(max_length=100, verbose_name='mv_reviews')),
                ('mvcategory', models.CharField(max_length=100, verbose_name='mv_category')),
                ('active', models.CharField(default='Y', max_length=100, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Director')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Address', unique=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Director', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor', unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Address')),
            ],
        ),
    ]
