# Generated by Django 2.2.6 on 2019-11-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actoraddress',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor'),
        ),
        migrations.AlterField(
            model_name='directoraddress',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Address'),
        ),
        migrations.AlterField(
            model_name='directoraddress',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Director'),
        ),
        migrations.AlterField(
            model_name='directormovies',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
