# Generated by Django 2.2.6 on 2019-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191124_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='active',
            field=models.CharField(default='Y', max_length=100, verbose_name='ctive'),
        ),
        migrations.AlterField(
            model_name='director',
            name='dexprc',
            field=models.IntegerField(verbose_name='mv_name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='dname',
            field=models.CharField(max_length=100, verbose_name='mv_name'),
        ),
    ]
